### ISSUE TITLE
wi-yahoo-n  not working

### ISSUE THREAD

**Issue by Em-Ant** [erikflowers/weather-icons#100]
I'm using the icons on codepen, and the selection classes for yahoo aren't working. Owm works correctly.

**Comment by erikflowers** [comment]
ahh this is a good find. I think the characaters are not in the :after

I will find this error in the build.

**Comment by erikflowers** [comment]
This is fixed.

**Comment by Em-Ant** [comment]
I've found another bug: the minified versions didn't work. (versions 2.0.1 - 2.0.4 from http://cdnjs.com/libraries/weather-icons ). I had to use the other 'normal' css. I dont know if I should open another issue.

Thank you anyway for the excellent job, i love this icon set. See you ...

**Comment by erikflowers** [comment]
It's working up to the 2.0.5 version now, CDNJS will need to update. It is supposed to self update.

The current version of the repo, the min file is fixed.

**Comment by Em-Ant** [comment]
Checked, works great now. Thanks.
