### ISSUE TITLE
2.0.1 CDN deprecated

### ISSUE THREAD

**Issue by martoncsikos** [erikflowers/weather-icons#101]
Hi Erik,

In the 'Getting Started' section in the docs the following CDN link is provided:
https://cdnjs.cloudflare.com/ajax/libs/weather-icons/2.0.1/css/weather-icons.min.css

The CSS hosted here is not working and not minified, probably a build issue.

2.0.5 works fine on below link so the doc should probably be updated, because it takes a bit of research to get it working this way.
https://cdnjs.cloudflare.com/ajax/libs/weather-icons/2.0.5/css/weather-icons.min.css

Nice icons btw!

**Comment by erikflowers** [comment]
Good catch, I have updated this.
