### ISSUE TITLE
Wind cardinals are not working

### ISSUE THREAD

**Issue by rajnadan** [erikflowers/weather-icons#103]

**Comment by erikflowers** [comment]
They're working when I try them, are you including the additional weather-icons-wind.css stylesheet with the default one?

The homepage at https://erikflowers.github.io/weather-icons/ uses the cardinal direction icons in the example with the same CSS and they're all working, they need to be written like this `<i class="wi wi-wind wi-towards-ne"></i>`

**Comment by AleksandrSidorov** [comment]
It would be nice to see some info about "additional weather-icons-wind.css" on the main webpage. Thank you for great project!

**Comment by erikflowers** [comment]
I added instructions to the wind sections. I will add it to the readme too.

**Comment by rajnadan** [comment]
Thanks. I thought it was <i class="wi wi-towards-ne"></i> initially
