### ISSUE TITLE
cdnjs's min link doesn't have wi-wu helpers

### ISSUE THREAD

**Issue by luisrudge** [erikflowers/weather-icons#107]
![image](https://cloud.githubusercontent.com/assets/941075/9978468/14c92b86-5f07-11e5-82de-5a9a240c068e.png)

**Comment by luisrudge** [comment]
the regular css has the helpers:

![image](https://cloud.githubusercontent.com/assets/941075/9978473/320b0160-5f07-11e5-9f81-9f289299356f.png)

**Comment by erikflowers** [comment]
I fixed this, but I am not sure how long it takes for cdnjs to auto-update. The tag number is 2.0.10

**Comment by luisrudge** [comment]
ok, thanks!
