### ISSUE TITLE
How to use TTF font?

### ISSUE THREAD

**Issue by edwinfinch** [erikflowers/weather-icons#110]
Hello, 

I am trying to use this awesome font in a new app for Pebble (smartwatch). I cannot figure out how to map the weather using your provided TTF font, where may I find the mappings of letters/characters to weather icons?

Thanks

**Comment by edwinfinch** [comment]
Okay, so after some digging through the SVG file I learned that your project uses unicode. Verified it with an earlier issue as well. I then learned that Pebble (does not support unicode)[https://forums.getpebble.com/discussion/4325/unicode-support, unfortunately. So therefore I cannot use your font :cry: 

Thanks anyway.

**Comment by erikflowers** [comment]
I am not familiar with the Pebble so I can't speak to the support of unicode. Seems like not supporting unicode is pretty crazy. Every single icon font is going to use the unicode private use areas, it's very strange they don't allow you to access it.

The font can be installed on your computer and then used in any graphics program to paste in the icons you want to use from the main weathericons.io page where you can just highlight an icon, and paste it into a graphics app where the font is set as weathericons. This is how designers and others put the icons inside their mockups or graphics. 

If you did this, you could save the icons you want as PNG, gif, or individual SVG's, whatever the Pebble supports.

**Comment by nogo10** [comment]
Hi Erik,

I wrote a function for a freecode camp sample that allows to do an approximate matching from weather API and returns the closest matching Wi-Code.
Seems like it's what Eric is looking for.. I used the function on my app and it renders your icons dynamically. 


regards
Steve

Date: Fri, 9 Oct 2015 07:49:50 -0700

**Comment by edwinfinch** [comment]
I mean no harm by posting this, only with intentions of helping: my co-partner found <a href="http://sm-artists.com/?page_id=925">this font</a> which is a similar style to this font (but with less characters) in case anyone is in my case of having to use actual letters/characters to show the weather icons.

Cheers.

**Comment by cpboyd** [comment]
@edwinfinch I saw this, and I just wanted to clarify: Pebble DOES support Unicode and I've used this font in a watch face.

You can use "\uXXXX" (where the X's represent the unicode hex) to define a Unicode character in C.
