### ISSUE TITLE
Barometric Pressure State

### ISSUE THREAD

**Issue by dmaidon** [erikflowers/weather-icons#117]
Icons for the state of barometric pressure:
Rising
Falling
Steady

**Comment by erikflowers** [comment]
Would that be like the existing pressure icon with an arrow indicator? Right now there are arrows that could be put right by it like this: 
<img width="52" alt="screen shot 2015-11-21 at 11 45 31 am" src="https://cloud.githubusercontent.com/assets/913115/11320200/6c6fe19e-9045-11e5-899f-455d708616f6.png">

Would this work?

**Comment by dmaidon** [comment]
I'll give it a try and see how that works with my setup

thanks
