### ISSUE TITLE
Problems with wind icons

### ISSUE THREAD

**Issue by barcik75** [erikflowers/weather-icons#131]
Thank you for a great icon to the weather. However, I have a problem. Icons from the wind did not appear at all on the page. Both stylesheets are loaded and visible. I do not know what could be the reason for not displaying icons. Page of icons: http://bartosz.francman.info/pl/11-rower/31-zimowo-rowerowo
Could you help?

**Comment by erikflowers** [comment]
That link doesn't work, can you try it again?

**Comment by erikflowers** [comment]
Sorry.

I need to update the documents, what you need to do is add wi-wind-direction to your html like this

````<i class="wi wi-wind-direction wi-from-e"></i>````

That's not clear. So it needs 3 classes, the wi class, the wi-wind-direction icon itself (the arrow), and then the direction class wi-from-e.

I tested it out on your page, and it solves the problem. Sorry about that.

**Comment by barcik75** [comment]
Ok. Thank you for fast response. Now it's works.

**Comment by gimmyfood** [comment]
Hi Erik, Just wanted to point out that the documentation on the main website still needs to be updated. 

A google search brought me to this answer which has worked but took me a while to work out that there was an issue to begin with.

p.s Thanks for all your work on this project!

**Comment by erikflowers** [comment]
It should be updated enough to make sense now. There was a lot wrong with it and I sort of forgot how the wind icons work.

**Comment by dsaw** [comment]
Hi, I was trying to use these icons with the same classes but wasn't working. It turns out you need to add the `wind` in between to get `wi wi-wind-direction wi-from-e` as given in the stylesheet files. [https://github.com/erikflowers/weather-icons/blob/master/sass/icon-classes/classes-wind-aliases.scss]()
The documentation needs
