### ISSUE TITLE
Weather Icon Generator Pack

### ISSUE THREAD

**Issue by raphaklaus** [erikflowers/weather-icons#136]
Hello! Thank you for this amazing icon pack! Really pretty.

However, I will use only 8 icons. There is no need to include all the pack, it's a weight more, unnecessarily.

I've suggest a web interface to select the wanted icons and generate the ttf,woff,eot files and the CSS.

I think to accomplish it, would be needed the SVG icons separated like Foundation Icons 3.

**Comment by erikflowers** [comment]
I think icomoon can just do this for you

https://icomoon.io/app/#/select




On January 27, 2016 at 3:15:44 PM, Raphael D. Pinheiro (notifications@github.com) wrote:

Hello! Thank you for this amazing icon pack! Really pretty.

However, I will use only 8 icons. There is no need to include all the pack, it's a weight more, unnecessarily.

I've suggest a web interface to select the wanted icons and generate the ttf,woff,eot files and the CSS.

I think to accomplish it, would be needed the SVG icons separated like Foundation Icons 3.

**Comment by raphaklaus** [comment]
Thank you! <3
