### ISSUE TITLE
Open Weather Map wrong condition or icon ID

### ISSUE THREAD

**Issue by mis3v** [erikflowers/weather-icons#149]
Hello,

First of all what a create Icon set, i really love it.
I have an issue with the open weather map icons:

For example:
On http://bugs.openweathermap.org/projects/api/wiki/Weather_Condition_Codes ID 701 is **Mist** but on https://erikflowers.github.io/weather-icons/api-list.html 701 indicates **showers**.

What is going wrong?

Thanks for the help!

Regards Niels

**Comment by erikflowers** [comment]
I didn’t do the mappings for these, but what probably happened is that showers was the closest icon this set had to mist. I have not created a mist icon.



On March 24, 2016 at 5:10:34 AM, mis3v (notifications@github.com) wrote:

Hello,

First of all what a create Icon set, i really love it.
I have an issue with the open weather map icons:

For example:
On http://bugs.openweathermap.org/projects/api/wiki/Weather_Condition_Codes ID 701 is Mist but on https://erikflowers.github.io/weather-icons/api-list.html 701 indicates showers.

What is going wrong?

Thanks for the help!

Regards Niels

**Comment by mis3v** [comment]
Hello Erik,

Thanks for the response, if you ask me the fog icon is pretty close and better for the mist condition ;). But fair enough. 

Keep up the great work :+1:
