### ISSUE TITLE
No Android support

### ISSUE THREAD

**Issue by tamutti** [erikflowers/weather-icons#159]
The font currently doesn't work with android devices like fontawesome does. Just using the identified shortcuts, f00d, doesn't produce anything. Not sure if I'm missing something. Any plans for a workable solution for mobile devices?

**Comment by ezokan** [comment]
This font seems to be working fine in my android app. I did the following:

- Copied `weathericons-regular-webfont.ttf` into my assests folder
- Copied `weathericons.xml` into my values folder
- Referenced string entry in the view of my xml layout:

`<TextView android:id="@+id/txvPrueba"`
`android:text="@string/wi_cloud"`
`android:layout_width="wrap_content"`
`android:layout_height="wrap_content"/>`
- Loaded the font in my code and set it for the appropriate Views:

`Typeface weatherFont = Typeface.createFromAsset(getContext().getAssets(), "fonts/weathericons.ttf");`
`txvPrueba.setTypeface(weatherFont);`

**Comment by tamutti** [comment]
Good to hear but how did you define your icons in the weathericons.xml?

**Comment by ezokan** [comment]
I don't defined anything, just use `https://github.com/erikflowers/weather-icons/blob/master/values/weathericons.xml` 
and put the resource in the TextView
`txvPrueba.setText(context.getString(R.string.wi_cloudy));`
I do not understand what you want to define

**Comment by tamutti** [comment]
I see what I was doing wrong now. Appreciate your quick responses and guidance in solving my problem.
