### ISSUE TITLE
Is there a json file for this page?

### ISSUE THREAD

**Issue by tommygebru** [erikflowers/weather-icons#162]
https://erikflowers.github.io/weather-icons/api-list

I want to be able to use the icons from your list I am already accessing the weather data api from openweathermap ....
So now I would like to learn how to bind openweather to your icons from this api-list....

https://erikflowers.github.io/weather-icons/api-list

**Comment by tommygebru** [comment]
Never mind I understand it now 👍

**Comment by braindonors** [comment]
Well, an example would be nice
