### ISSUE TITLE
Rename folder font to fonts, similar to font-awesome

### ISSUE THREAD

**Issue by ssc-hrep3** [erikflowers/weather-icons#165]
Hi there

The provided CSS file of weather-icons has an URL linking to the font files in the folder `font`. Font Awesome however uses the path `fonts`. After a build of my CSS files, I need to put the weather-icon fonts into `font` and the font-awesome fonts into `fonts`. I use Sass for my project, so using less only for this would be somewhat ridiculous.

Would it be possible to move the fonts into the `fonts` folder instead of the `font` folder?

Best wishes
Sebastian

**Comment by erikflowers** [comment]
I would change the CSS file itself. I can't change the font to fonts directory without breaking every other person's install. I know it's not consistent with Font Awesome as well. At one point it was fonts, but there was a reason to change it to font, I don't recall what the reason was.

**Comment by theCrius** [comment]
I know this is an old issue but you can easily fix this by writing a less file with something like this:

```
@import "/path/to/less/weather-icons.less";
@wi-path: "../fonts";
```

Of course the same thing can be done with SASS.
