### ISSUE TITLE
Icon character mapping

### ISSUE THREAD

**Issue by vadrian89** [erikflowers/weather-icons#177]
Is there a way to get hold of characters mapping for truetype fonts?  
In my project I cannot use CSS neither can manipulate SVG to get render based on glyph code(can only show an entire SVG file)

**Comment by erikflowers** [comment]
I don't think I get the question, the character unicode values are all referenced in the css (or glyphs) file, but that's all I know. The artwork is all in the glyphs file too, but the SVG that is output is just something FontSquirrel outputs, I don't actually know what it's for.

**Comment by vadrian89** [comment]
I see, actually this answered more than I hoped :). Thanks
