### ISSUE TITLE
Flutter wrapper

### ISSUE THREAD

**Issue by Kenny11CZ** [erikflowers/weather-icons#198]
Hello,

I've made simple wrapper for Flutter and pushed it to official repo, are you okay with it?
[Pub link](https://pub.dartlang.org/packages/weather_icons_flutter)
[Git link](https://github.com/Kenny11CZ/weather_icons_flutter)

**Comment by Kenny11CZ** [comment]
Glad to hear that, closing :)

**Comment by final0101010** [comment]
Good Luck with everything!
