### ISSUE TITLE
add inverse icons for moon

### ISSUE THREAD

**Issue by jersu11** [erikflowers/weather-icons#20]
The new moon icons in 1.2 are great. I'd love to see an addition of these moon icons inverted, with something like wi-moon-alt-waxing-quarter or wi-moon-inverse-old

When displaying the moon with a light color on a dark background (as in a bright white moon against the black of space), the area which appears illuminated is the opposite of what one would expect. For example, with a style of "color:#fff; background-color:#000" for wi-moon-full, you get a donut, not a disc.

**Comment by erikflowers** [comment]
Alternate icons are added that are inverted.
