### ISSUE TITLE
Cannot see Humidity and barometer

### ISSUE THREAD

**Issue by xTheDoctah** [erikflowers/weather-icons#205]
I used npm to download the packaged and imported the css file on angular css, using 
@import '~weather-icons/css/weather-icons.min.css'; . The other icons work like a charm.

**Comment by afternoon2** [comment]
I installed `weather-icons2` from npm and then imported two css files, and it worked for me.

```javascript
import 'weather-icons2/css/weather-icons.min.css';
import 'weather-icons2/css/weather-icons-wind.min.css';
```

**Comment by PA55ION** [comment]
@afternoon2 Thank you. your solution work for me :)
