### ISSUE TITLE
Weather.io appears to be a parking page.

### ISSUE THREAD

**Issue by deawar** [erikflowers/weather-icons#223]
Weather.io appears to be a parking page.

**Comment by jadeli1720** [comment]
I don't know if this helps, but here is the site you need: http://erikflowers.github.io/weather-icons/

**Comment by deawar** [comment]
Jade,
Thank you!
Hope you have a great day,
Dean Warren

**Comment by dshanske** [comment]
@fox91 Are you joining in on handling issues in this repo? I know it has been abandoned and looking for a maintainer for a bit.

**Comment by fox91** [comment]
Hi @dshanske, I'm trying to solve open issue, merge PR where possible and maybe restart the project.

**Comment by deawar** [comment]
@fox91 would be interested in helping if possible.

**Comment by dshanske** [comment]
As a user, I'd like to help any way I can....just can't draw.

**Comment by fox91** [comment]
Hi @deawar and @dshanske,
can you check the PR or solve the issue still open?
I think it can be a good starting point.
