### ISSUE TITLE
Cloudy Icon with "Open Weather Map"

### ISSUE THREAD

**Issue by responsemlanger** [erikflowers/weather-icons#230]
The API for Open Weather Map shows that the IDs 801-804 are only use for Clouds (few, scattered, broken, overcast). The icon for these IDs in your repository shows clouds with gusts.

Can we change this?

**Comment by deadlocker8** [comment]
I noticed the same problem and tried to fix it in #232. As I am new to less and sass I may have missed updating some files but the new generated weather-icons.min.css should work.

**Comment by fox91** [comment]
@responsemlanger thanks for your report.
@deadlocker8 thanks for your fix.
