### ISSUE TITLE
It seems that there are spaces in the file name. (filename_.svg)

### ISSUE THREAD

**Issue by reefle** [erikflowers/weather-icons#248]
Hi. weather-icons is a great project.
but It seems that there are spaces in the file name.

![image](https://user-images.githubusercontent.com/83553788/127088603-bf3f5dea-c3e8-4445-a4bc-0c84f14ca8cb.png)

I found this ? while incorporating weather-icons into emoji-mart-vue.
Some icon files cannot be loaded because there is a space character inserted between the extension and the file name.
The file path in values/weathericons.xml is fine.

![image](https://user-images.githubusercontent.com/83553788/127099889-5e5ad4c3-2b26-4ed7-a3f8-bf8c9ae557de.png)

**Comment by fox91** [comment]
Hi @reefle, unfortunately the SVG aren't perfect on a lot of aspect (not only on the name).
I'm currently working on version 3.* with this and other issue fixed.
If this issue cause you trouble feel free to submit a PR.

**Comment by Travelbacon** [comment]
I had today issues with the white spaces. And as you can see, I made a small PR.

**Comment by fox91** [comment]
Hi @Travelbacon, I've merged your PR.
Thanks
