### ISSUE TITLE
weather-icons.min.css.map

### ISSUE THREAD

**Issue by Shiviip** [erikflowers/weather-icons#250]
Console is saying to get 'weather-icons.min.css.map’ file, however it isn’t available on the download.

I’ve re-downloaded the folder and that specify file is nowhere to be seen.. some assistance would be great.

Thanks

**Comment by fox91** [comment]
Actually there isn't `.css.map` file in this project.
What you see in the console is just a warning, not a real problem, and you can disable the use of source maps in your console if you don't want to see the message anymore.
