### ISSUE TITLE
Moon icons are slightly inaccurate

### ISSUE THREAD

**Issue by crsaracco** [erikflowers/weather-icons#28]
The "Gibbous" moon icons are inaccurate - the dark part should be concave, not convex.

See http://stardate.org/nightsky/moon for details. Compare 2014-09-03 through 2014-09-06 to wi-moon-waxing-gibbous

Also, why is quarter not a straight line?

EDIT: derp I can't even use the right words for concave and convex.

**Comment by erikflowers** [comment]
inverted moon  icons have been added under an alt-class
