### ISSUE TITLE
CDNJS automatic pull request version issue

### ISSUE THREAD

**Issue by adaptive** [erikflowers/weather-icons#46]
CDNjs - No more manual pull request #3638
https://github.com/cdnjs/cdnjs/issues/3638

weather-icons is now pull into CDNjs automatically. This created a small version number issue, but is not a big deal. when weather-icons brins in version 1.4 this might correct.

The automatic pull just guarantees that more users get faster access to earlier versions via a free cdn.
https://github.com/cdnjs/cdnjs

**Comment by erikflowers** [comment]
I am not sure how to fix this, but I am going to be updating to a whole new 2.0 version of the project this week, and CDNJS will be a part of it. 
https://github.com/erikflowers/weather-icons/issues/85
