### ISSUE TITLE
Request: Icon for air pressure (barometer)

### ISSUE THREAD

**Issue by r0b-** [erikflowers/weather-icons#49]
Maybe something like a gauge?

Thanks a lot! 
Rob

**Comment by erikflowers** [comment]
I can mark this down for the next update.

**Comment by stelgenhof** [comment]
Yes, I would love to see an icon for atmospheric pressure too. Just the one I am missing :)

**Comment by erikflowers** [comment]
added for 2.0 this week https://github.com/erikflowers/weather-icons/issues/86
