### ISSUE TITLE
Fixed width class

### ISSUE THREAD

**Issue by Akeru** [erikflowers/weather-icons#50]
Much like the fa-fw class used by FontAwsome. This would make tabular data look nicer.

**Comment by erikflowers** [comment]
That's a good idea. I don't have a solid plan on when to add utility classes, but if you wanted to do it now you can just add a width that suits your needs to the .wi class and it will work right away.

**Comment by erikflowers** [comment]
adding 2.0 due out this week.

**Comment by Akeru** [comment]
:+1:
