### ISSUE TITLE
BUG: The wind icons doesn't work

### ISSUE THREAD

**Issue by edgren** [erikflowers/weather-icons#52]
Hi!

The wind direction icons doesn't work at all. None of the wi-wind-default._{number}-deg work but all the other icons works.

**Comment by erikflowers** [comment]
This is a bad typo on the doc page. It does work if you use it like this

    <i class="wi wi-wind-default _270-deg"></i>

On the doc page, it should probably say "wi-wind-default _270-deg" since that is how you'd write it in HTML, not Less.

**Comment by edgren** [comment]
Awesome! Please add this information in the documentation :)

**Comment by erikflowers** [comment]
It's updated on the doc page. It should be noted there is a space between the 2 classes, it's

wi-wind-default
_270-deg

I couldn't start classes with numbers, and wanted it to be different than a dash. Mostly so that it can be easier maintained in the Less file, like this:

```less
 .@{weather-icons-prefix}-wind-default {
  &._0-deg {.wind-rotate(0deg); }
  &._15-deg {.wind-rotate(15deg); }
  &._30-deg {.wind-rotate(30deg); }
  &._45-deg {.wind-rotate(45deg); }
  &._60-deg {.wind-rotate(60deg); }
  &._75-deg {.wind-rotate(75deg); }
  &._90-deg {.wind-rotate(90deg); }
  &._105-deg {.wind-rotate(105deg); }
  &._120-deg {.wind-rotate(120deg); }
  &._135-deg {.wind-rotate(135deg); }
  &._150-deg {.wind-rotate(150deg); }
  &._165-deg {.wind-rotate(165deg); }
  &._180-deg {.wind-rotate(180deg); }
  &._195-deg {.wind-rotate(195deg); }
  &._210-deg {.wind-rotate(210deg); }
  &._225-deg {.wind-rotate(225deg); }
  &._240-deg {.wind-rotate(240deg); }
  &._255-deg {.wind-rotate(255deg); }
  &._270-deg {.wind-rotate(270deg); }
  &._285-deg {.wind-rotate(295deg); }
  &._300-deg {.wind-rotate(300deg); }
  &._315-deg {.wind-rotate(315deg); }
  &._330-deg {.wind-rotate(330deg); }
  &._345-deg {.wind-rotate(345deg); }
}
```
