### ISSUE TITLE
Forecast.io compatibilty

### ISSUE THREAD

**Issue by bradoyler** [erikflowers/weather-icons#55]
FYI. You'd only need to add/alias 5 class names to have full compatibilty with the icon names used in the Forecast.io API. 
```
wi-clear-day 
wi-clear-night 
wi-wind
wi-partly-cloudy-day
wi-partly-cloudy-night
```
via this page: https://developer.forecast.io/docs/v2

> icon: A machine-readable text summary of this data point, suitable for selecting an icon for display. If defined, this property will have one of the following values: clear-day, clear-night, rain, snow, sleet, wind, fog, cloudy, partly-cloudy-day, or partly-cloudy-night.

**Comment by erikflowers** [comment]
This is a part of the 2.0 update due this week.
