### ISSUE TITLE
.ttf file

### ISSUE THREAD

**Issue by SexyBlueTiger** [erikflowers/weather-icons#58]
Hi there!  Wonderful icon set you've created.  Am I wrong in assuming that the .ttf file should have the icons in it?  When I installed it on my machine it looks like a regular font with A-Z.  I'm creating an application in WPF/C# and was hoping to use these there.

Cheers

**Comment by erikflowers** [comment]
Font icons like this don't use the regular range of characters, they use the Private Use Areas of Unicode: http://en.wikipedia.org/wiki/Private_Use_Areas, so you have to call the characters directly by the hex value. For instance, The first icon is #F000, Day Cloudy Gusts. Then one like Day Storm Showers is #f00e.

I can't tell you how to access those in your languages, but I am sure it's out there on google somewhere. They are glyphs, they're just not on any "keyboard" keys.

Now, if you're trying to use the hex values and it's not working, I am not sure on that one.

**Comment by SexyBlueTiger** [comment]
Thank you very much Erik :) with your information and a bit of googling around WPF and Private_Use_Areas I found out that "&#xf000;" is what I needed to produce "Day Cloudy Gusts".  I look forward to using your font very much in my personal project! :+1:

**Comment by Maikell84** [comment]
This hint helped me, too. Thank you very much!
Wouldn't it be nice, if there was an overview in the documentation with all the icons and their relating hex-codes?

**Comment by erikflowers** [comment]
a cheatsheet of hex's and also a way to just select the icon and copy/paste into a design app will be in 2.0 due out this week

added for 2.0 this week https://github.com/erikflowers/weather-icons/issues/86
