### ISSUE TITLE
Inconsistencies with Fonts Displaying in Chrome

### ISSUE THREAD

**Issue by LostPine** [erikflowers/weather-icons#67]
I have implemented Awesome Weather Pro and found that Safari and IE display beautiful icons.  Yet Chrome does not.  It appears that some ISPs, mine in particular, are not passing .woff files through to the browser.  Research seems to indicate two forms of action: (modify the IIS servers) or change the order in which .css references .tiff, .svg, and .woff fonts when they are called in the browser.  Threads on the web indicate that .svg, if called first will work with Chrome.  

I cannot find any real support threads on what the proper fix for this should be.  ISPs will not take kindly to altering their servers so I am hoping that there is a coding solution that can be implemented by plugin developers that solves this issue.  Fonts are great but until .woff issues are stabilized, plugins like Awesome Weather Pro fall short of expectations for Chrome users.

**Comment by Craytor** [comment]
First off, this is weather-icons, not Awesome Weather Pro, so it sounds like you may have contacted the wrong entity. Also, with that being said, it sounds like the problem would be on AWP's end, not on weather-icons end since all weather-icons is doing is creating an amazing library of icons - that's it.

**Comment by erikflowers** [comment]
The ordering of the CSS can be changed easily by anyone using Weather Icons. Having said that, like Craytor says above, I am not affiliated with the Awesome Weather Pro widget. Unfortunatley, I have no way of knowing who uses Weather Icons. It's the #1 google result for "weather icons" (clever name), but I only ever find out that people use it when I happen to see it somewhere, somehow.

I'm gonna close this as there's nothing I can do. I'd post it to their Wordpress support forum all plugins have.

**Comment by LostPine** [comment]
I understand, thank you.  The problem with this issue has been that Google says it is fixed, the plugin developer says it isn’t a problem, yet the blogs are filled with sites like ours that struggle for the solution.  I am sure eventually it will be worked out.  Your icons are great.  It looked like you had supplied the coding to the plugin developer but it was not structured, just packed text.  I am relatively new to WordPress and do not feel comfortable altering that type of coding. Chrome is the most widely used browser on our site so I tend to watch those issues more closely.

 

I appreciate your feedback.

 

Bob Samson

**Comment by LostPine** [comment]
I agree, icons are awesome.  Plugin developer has not been too responsive on the issue.  I was looking for ideas on coding and whether anyone had fixed this issue with Chrome.  It was my opinion that the plugin developer was not familiar enough with .woff issues and thought that the Eric Flowers might have tips.  I plan to keep searching.  It is hard to believe that with Chrome so popular, there is not a simple solution.  Every other browser works perfectly.

 

Thanks for your feedback.
