### ISSUE TITLE
2 new Icons: moonrise and moonset

### ISSUE THREAD

**Issue by Wittke** [erikflowers/weather-icons#68]
Hi,
i need 2 new icons for moonrise and moonset.

Such as...
  https://cdn1.iconfinder.com/data/icons/hawcons/32/700455-icon-41-moonrise-256.png
  https://cdn1.iconfinder.com/data/icons/hawcons/32/700456-icon-42-moonset-256.png

Can you help me?

Thank you and goodbye

**Comment by erikflowers** [comment]
I think these are appropriate, I'll add them to my list of new icons.

**Comment by erikflowers** [comment]
added for 2.0 this week https://github.com/erikflowers/weather-icons/issues/86
