### ISSUE TITLE
Icon Recommendations

### ISSUE THREAD

**Issue by willchapman** [erikflowers/weather-icons#69]
The system I am using is missing some icons that may or may not be a good idea to add.

Tsunami
Earthquake
Fire (Smoke is close)
Volcano

Mostly natural disasters, but since hurricane and tornado are in there figured I would throw it out as a suggestion.

**Comment by erikflowers** [comment]
That's a good idea. Didn't consider natural disasters before but sounds like a worthwhile addition.

**Comment by Craytor** [comment]
+1 Good idea!! :D

**Comment by socki03** [comment]
Maybe a default emergency one as well, in case it doesn't exactly fit.  Like Earthquake may be a tough icon, but the triangle exclamation mark urgency icon would work in a range of extreme cases.
![warning_sign](https://cloud.githubusercontent.com/assets/1022455/7595140/d886029c-f8aa-11e4-909e-cb3cd29083e7.jpg)

**Comment by erikflowers** [comment]
added for 2.0 this week
https://github.com/erikflowers/weather-icons/issues/86
