### ISSUE TITLE
Moon Phases backwards with default black font with white background

### ISSUE THREAD

**Issue by ajwaka** [erikflowers/weather-icons#72]
I feel the moon phases are essentially backwards when using black font on a white background (common scenario).  The "New Moon" shows as an empty circle with a black outline which I feel should be a "Full Moon".  A Full moon shows as a filled black circle - which again w/ default settings looks more like a New Moon.

I understand the logic behind how it's working (full moon being filled in).

To get a close "fix" - I've had to reference the opposite of what the icon actually is.  http://screencast.com/t/pgqoO0kZXAc  Maybe the moon icons themselves could be a full circle (waning/waxing) so even with it being as is - if I have black font on white - That way in my example the "First Quarter" would be a full circle - filled in on the left - and the right side being white.

**Comment by erikflowers** [comment]
I am not sure on the moon icons what I want to do with it. When I look at it, light or dark, it makes sense to me - the parts of the icon that have pixels are the parts of the moon you can see. I understand what everyone is saying - having a black crescent on a white background might look like "the black part is the shadow", but I personally can't see it that way. 

Here is how they are now.
![](https://cloud.githubusercontent.com/assets/913115/5239094/832c457e-7888-11e4-9da6-de63cb023575.png)

So if they were inverted, essentially the first icon in the top, waxing-crescent-1, inverted would be waning-gibbous-1 as we're just using the same shape but saying "in one, the pixels represent the visible moon, and in the other, the pixels represent the shadow."

![](https://cloud.githubusercontent.com/assets/913115/5239096/98dbd3a8-7888-11e4-9bd9-2b2a734f6e87.png)

Again, I do understand the thought. But I still think that pixels = the moon's surface, whether it's light or dark background. So a full moon would be a black disk on white, or a white disk on black. A new moon would be a thinly white stroked hollow circle on black, and a thinly stroked black circle on white.

I am going to close this just so it is not hanging open, but it is on my list of todo items for version 2.0 due out this week. This might take some thought though and be in a later update if a better solution comes around.

https://github.com/erikflowers/weather-icons/issues/85

**Comment by erikflowers** [comment]
Inverted icons have been added under an alt-class

**Comment by ajwaka** [comment]
This is perfect!  Thank you Erik - don't forget to mark it completed on your 2.0 list #85
