### ISSUE TITLE
Full 360-degree CSS transform for wind bearing

### ISSUE THREAD

**Issue by 47ronin** [erikflowers/weather-icons#79]
For some reason, using the standard '_255-deg' etc. classes was not working in my webapp (I swear, I tried!) so I wrote my own transforms after looking at your CSS. My method does not create set-in-stone angles but will pull any specified degree of wind bearing and rotate the icon to match that angle. (Written in AngularJS)

Controller: https://github.com/47ronin/weatherview/commit/497f3516bf3ed1837a2568b40a6c162d7241b7db

HTML: https://github.com/47ronin/weatherview/commit/500c44d3f55e42e8d496e51eda34e0d2799f79fd

**Comment by stenmuchow** [comment]
Its an error in the latest tag which the degrees are missing  a '.' prefix in front of the class in the css. If you are using bower did a bower install from master or the latest commit from the log. I had the same issue...

**Comment by 47ronin** [comment]
@stenmuchow Yes, I used bower install from master —good to know it wasn't just me!

**Comment by erikflowers** [comment]
These are all new and fixed in 2.0.
