### ISSUE TITLE
single raindrop, snowflake

### ISSUE THREAD

**Issue by bakman2** [erikflowers/weather-icons#84]
single raindrop, snowflake icons

And as addressed in #62, please consider the use cardinal wind directions, programmatically it makes things a lot easier (currently it has to be translated in functions). 

Same applies for moons, if one calculates the phase of the moon it comes back with a number.

Thumbs up for your work!

**Comment by erikflowers** [comment]
Snowflake is already there under wi-snowflake-cold
a single raindrop can be added

Monitor progress here https://github.com/erikflowers/weather-icons/issues/86
