### ISSUE TITLE
2.0 List

### ISSUE THREAD

**Issue by erikflowers** [erikflowers/weather-icons#85]
Running list of major 2.0 changes

- [x] Sass version
- [x] Figure out how to use Less/Sass loop to generate classes off variables instead of doing it all twice (now 4) times. OR, figure out how to generate Less and Sass from a single variable list that has class name and hex value (text file? other language? ....)
- [x] Make index page glyphs copyable for copy/paste into design apps
- [x] Make offline cheatsheet for copy/paste and name finding
- [x] Figure out of it is possible to generate Github Pages and Cheatsheet HTML from the same source file of class names and hex values.
- [x] wind direction alternative - cardinal vs. source directions
- [x] beaufort spelling
- [x] new folder structure
- [x] Have hex value listed on cheatsheet
- [x] Add a metric ton of icons... too many to try listing
- [x] Yahoo, openweather, forecast.io API class options
- [x] get rid of private sandbox repo
- [x] cooler weathericons.io homepage
- [x] Investigate level of inclusion of FontAwesome style manipulation (width, sizes, etc) for 2.0 instead of future feature releases.
- [x] Fixed width class
- [x] figure out CDNJS issue
- [x] investigate NOAA icon mapping
- [x] Start using branches for feature updates
- [x] moon phase alternatives

**Comment by XzAeRo** [comment]
Hey! FYI you can (use task lists in Github)[https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments]

**Comment by ajwaka** [comment]
Thanks Erik I'm posting  w/ regards to #72  he moon phases - what about keeping the "moon border" along w/ the shadow.  EG:
![Image of unif098](http://content.screencast.com/users/ajwaka/folders/Jing/media/30e8d8c1-4223-46b5-8472-a8edd7745c82/2015-08-03_0948.png) 

This would be more obvious for my site users on a deer hunting site - and it would be up to me to choose the opposite (using full moon for new moon, etc)

Thanks much!

**Comment by 47ronin** [comment]
Great work with 2.0 btw!
