### ISSUE TITLE
Missing icon: wi-wind-direction

### ISSUE THREAD

**Issue by r0b-** [erikflowers/weather-icons#89]
Hi,

I can't find the "wi-wind-direction" icon in the 2.0.0 css...

Thanks

**Comment by erikflowers** [comment]
Can you elaborate? All the wind direction classes are in the weather-icons-wind.css file, since there are so many. What icon are you looking for?

**Comment by r0b-** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/1260055/9271071/578c69e4-4277-11e5-8904-55fe8de08779.PNG)
It's an icon in the Neutral section in the docs...
Because the wind.css is a huge file it would be nice to have this icon in the standard set.

Thanks

**Comment by erikflowers** [comment]
Oh I see, it needs a CSS class alone in weather-icons.css. I can add that no problem. Good find.

**Comment by r0b-** [comment]
Thanks a lot!

**Comment by erikflowers** [comment]
This was present in the SCSS but not Less. I use the Less, so it is fixed now.

**Comment by leoherzog** [comment]
This icon is great, but it's missing from the SVG set?
