### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by jamwaffles** [erikflowers/weather-icons#9]
Could you add [Bower](http://bower.io/) support to weather-icons? It would make installing/using it quite a bit simpler.

**Comment by adityamukeshthakur** [comment]
@DaAwesomeP  your solution worked for me. Thanks!

**Comment by DaAwesomeP** [comment]
@adityamukeshthakur glad to here! I guess that I never made a `bower.json`... Maybe I'll do that. The `main` option makes build scripts (like Gulp) easier to use with libraries.
