### ISSUE TITLE
Moon phases

### ISSUE THREAD

**Issue by bakman2** [erikflowers/weather-icons#94]
Would it be possible to add the moon phases from 1 to 28 (0-27) ?
I have to write a function to map them against the names (I get a number for the phases).

**Comment by erikflowers** [comment]
I think there could be an alias like this in the less/sass.

```
  .wi-moon-phase-0 {
    .wi-moon-waxing-gibbous-3; 
  }
```

Which one is 0? Or as I have them listed, are they properly 0-27?

**Comment by bakman2** [comment]
0(or 1) would be a new moon ? like you have listed them yes.
Alias, just like the wind directions ? thanks for those!

**Comment by erikflowers** [comment]
I just realized I only have 26 moon icons, not 28. Will have to look in to how this can work.

**Comment by erikflowers** [comment]
this is fixed, and also I added inverted versions of the moon under an -alt class

**Comment by bakman2** [comment]
thanks Erik!
