### ISSUE TITLE
Add ability to override variables in SASS version

### ISSUE THREAD

**Issue by Va1** [erikflowers/weather-icons#95]
Hey, guys!

I needed to override the path to fonts directory and found a variable in sources - `$wi-path` ([here](https://github.com/erikflowers/weather-icons/blob/master/sass/weather-icons-core.scss#L2)). I've tried to override it before importing the main SCSS file of the package but failed. Then I've looked carefully again and found out that it can not be overridden due to missing `!default` after its value. This applies to all those variables next to `$wi-path`. I can submit a PR.

**Comment by erikflowers** [comment]
This is specific to Sass and not Less? This is my first go with Sass and not less. I will look in to this, but also feel free to PR.

**Comment by Va1** [comment]
Yes, this is specific to SASS. This is one of my first projects with SASS and I just ran into a fact that variables are loading in different way in it. In LESS you can do overrides anywhere, but in SASS you need to add `!default` to the variables that should be overridden before being declared. [Some info](https://robots.thoughtbot.com/sass-default).

**Comment by Va1** [comment]
Also [here](https://css-tricks.com/sass-vs-less/), "Variable Handling" section.

**Comment by Va1** [comment]
Looks nice! It would be also cool if you bump the package version so the fix will be available over package managers. Thank you.

**Comment by erikflowers** [comment]
Would that require adding a new tag and pointing the bower file there? I still don't quite grasp the package manager management.

**Comment by Va1** [comment]
I guess so. And you need to update version (to 2.0.2, I think, as it is a fix).

**Comment by Va1** [comment]
Good!
