### ISSUE TITLE
No icons when using minified CSS

### ISSUE THREAD

**Issue by tzd** [erikflowers/weather-icons#98]
First I want to thank you for this great icons.
I'm using bower and it seems that minified css contains older code (1.3), please check https://github.com/erikflowers/weather-icons/blob/master/css/weather-icons.min.css
When I include non-minified wersion all works ok, but when I include minified version there is no icons.

**Comment by erikflowers** [comment]
This file's comments at the top of the file are mistakenly not updated, but it does have the new icons in it, like the moon phases, the train, the hurricane warnings, etc. I will update the files, but my testing of the file does work.

**Comment by tzd** [comment]
Hi, please compare minified and non-minified version, in minified version there is no @font-face defined, there are no .wi-rotate-* and .wi-flip-* classes etc.

**Comment by erikflowers** [comment]
You are right, I totally screwed up the Less/Sass for the minified files by leaving out the new includes. This should be fixed now as it is pulling the exact same files as the regular version

https://github.com/erikflowers/weather-icons/blob/master/less/weather-icons.min.less

**Comment by tzd** [comment]
Great, thank you.
